{
 "title": "player_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "club",
    "label": "club",
    "query": "label_values(goals_scored , club)"
   },
   {
    "name": "player",
    "label": "player",
    "query": "label_values(goals_scored {club=\"$club\"} , player)"
   },
   {
    "name": "image",
    "label": "image",
    "query": "label_values(goals_scored {club=\"$club\" , player=\"$player\"} ,image)"
   }
  ]
 },
 "panels": [
  {
   "title": "$player",
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "content": "\n\n<img src=\"$image\" width=\"300\", height=\"300\">\n\n",
   "targets": [
    {
     "expr": "goals_scored{player=\"$player\"}"
    }
   ]
  },
  {
   "title": "Games Start",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "starts{club=\"$club\", player=\"$player\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Goals Scored",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "goals_scored{club=\"$club\", player=\"$player\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Assists Made",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "assists{club=\"$club\",player=\"$player\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Minutes Played",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "minutes_played{club=\"$club\",player=\"$player\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "$club",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "starts{club=\"$club\"}",
     "legendFormat": "{{player}}"
    }
   ]
  }
 ]
}