{
 "title": "player_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "club",
    "label": "club",
    "query": "label_values(goals_scored , club)"
   },
   {
    "name": "player",
    "label": "player",
    "query": "label_values(goals_scored {club=\"$club\"} , name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Games Start",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "starts{name=\"$player\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Goals Scored",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "goals_scored{name=\"$player\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Assists Made",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "assists{name=\"$player\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Assists Made",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "minutes_played{name=\"$player\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "$club",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "starts{club=\"$club\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}